// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	cli2 "github.com/txgruppi/study-server/cli"
	"github.com/txgruppi/study-server/database"
	"github.com/txgruppi/study-server/http"
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func Wire() (*cli.App, error) {
	store, err := database.Wire()
	if err != nil {
		return nil, err
	}
	runner, err := http.Wire(store)
	if err != nil {
		return nil, err
	}
	app := cli2.Wire(runner)
	return app, nil
}
